name: runner

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

env:
  MCV_USERNAME: ${{ secrets.MCV_USERNAME }}
  MCV_PASSWORD: ${{ secrets.MCV_PASSWORD }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute task
        run: python main.py

      - name: Commit records to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update records
